import {
  PrescriptionAnalyzeResponseDto,
  FastApiHttpErrorDto,
} from '../../types/api.types';

/**
 * 1. CONFIDENT RESPONSE FIXTURE
 * Acute Bronchitis & Routine Multi-Drug Script (Augmentin 625 Duo)
 */
export const CONFIDENT_RESPONSE_FIXTURE: PrescriptionAnalyzeResponseDto = {
  status: 'success',
  meta: {
    request_id: 'req-aura-20260905-001',
    timestamp: '2026-09-05T19:25:00Z',
    processing_time_ms: 680,
    model_version: 'aura-swin-v3.4-clinical',
    pipeline_stages_completed: 7,
  },
  document_telemetry: {
    estimated_dpi: 300,
    contrast_ratio: 4.85,
    skew_angle_deg: 0.4,
    illegibility_score: 0.04,
    orientation: 'Portrait',
  },
  data: {
    accession_id: 'DEMO-RX-01',
    script_sample_key: 'rx-sample-1',
    scenario_title: 'Standard Antibiotic & Gastroprotective Script',
    scenario_subtitle: 'Illustrative demonstration scenario with clear cursive handwriting',
    difficulty_tag: 'Clear Handwriting',
    overall_status: 'VERIFIED',
    document_confidence: 0.95,
    patient_info: {
      name: 'Demo Patient',
      age_gender: 'Adult / Demo',
    },
    prescriber_info: {
      name: 'Example Prescriber, M.D. (Internal Medicine)',
      qualifications: 'Consulting Physician (Illustrative Demo)',
      registration_no: 'Demo Reg. No. 00000',
      clinic_name: 'Example Clinical Practice',
      clinic_address: 'Sample Clinic Address (Evaluation Demo)',
    },
    extracted_entities: [
      {
        field_key: 'medicine_name',
        field_label: 'Medicine Name',
        raw_value: 'Augmentin 625 Duo',
        normalized_value: 'Augmentin 625 Duo',
        confidence: 0.96,
        status: 'confident',
        stroke_source: 'Prescription Line 01 · Pen Stroke #1',
        bounding_box: { x: 12, y: 30, width: 78, height: 12 },
        explanation: 'Cursive stroke matches canonical Amoxicillin/Clavulanate template with high geometric fidelity.',
      },
      {
        field_key: 'dosage',
        field_label: 'Dosage / Strength',
        raw_value: '625 mg',
        normalized_value: '625 mg (Amoxicillin 500mg + Clavulanate 125mg)',
        confidence: 0.95,
        status: 'confident',
        stroke_source: 'Prescription Line 01 · Pen Stroke #2',
        bounding_box: { x: 50, y: 30, width: 22, height: 12 },
        explanation: 'Numerical digits 6-2-5 clearly distinguished with zero stroke ambiguity.',
      },
      {
        field_key: 'frequency',
        field_label: 'Frequency',
        raw_value: '1-0-1',
        normalized_value: '1-0-1 (Twice daily: Morning & Night)',
        confidence: 0.94,
        status: 'confident',
        stroke_source: 'Prescription Line 01 · Pen Stroke #3',
        bounding_box: { x: 74, y: 30, width: 16, height: 12 },
        explanation: 'Standard Indian posology shorthand parsed: Morning 1, Afternoon 0, Night 1.',
      },
      {
        field_key: 'duration',
        field_label: 'Duration',
        raw_value: '5d',
        normalized_value: '5 days',
        confidence: 0.93,
        status: 'confident',
        stroke_source: 'Prescription Line 01 · Pen Stroke #4',
        bounding_box: { x: 80, y: 30, width: 10, height: 12 },
        explanation: 'Numeral 5 and duration abbreviation "d" clearly isolated and verified.',
      },
      {
        field_key: 'abbreviation',
        field_label: 'Medical Abbreviations',
        raw_value: 'PC',
        normalized_value: 'PC (Post Cibum / After meals)',
        confidence: 0.95,
        status: 'confident',
        stroke_source: 'Prescription Line 01 · Pen Stroke #5',
        bounding_box: { x: 88, y: 30, width: 8, height: 12 },
        explanation: 'Latin clinical abbreviation "PC" accurately decoded to post-cibum (after food).',
      },
    ],
    validation_evidence: {
      candidate_name: 'Augmentin 625 Duo Tablet',
      matched_entity_name: 'Augmentin 625 Duo Tablet',
      generic_salt: 'Amoxicillin (500mg) + Potassium Clavulanate (125mg)',
      validation_status: 'cdsco_approved',
      status_badge_text: 'CDSCO Approved · Indian Pharmacopoeia',
      rxnorm_cui: '213169',
      cdsco_schedule: 'Schedule H (Prescription Only Antibacterial)',
      atc_code: 'J01CR02',
      therapeutic_class: 'Beta-lactamase inhibitor combination / Broad-spectrum antibacterial',
      indications: 'Bacterial respiratory infections, acute bronchitis, community-acquired pneumonia',
      evidence_source: 'CDSCO National List of Essential Medicines (NLEM) 2022 & US NLM RxNorm',
      reference_url: 'https://rxnav.nlm.nih.gov/REST/rxcui/213169',
      alternatives: [
        {
          name: 'Clavam 625 Tablet',
          generic: 'Amoxicillin 500mg + Clavulanic Acid 125mg (Alkem)',
          similarity_score: 0.93,
          notes: 'Equivalent bioavailable formulation widely dispensed in India.',
        },
        {
          name: 'Moxikind-CV 625 Tablet',
          generic: 'Amoxicillin 500mg + Clavulanic Acid 125mg (Mankind)',
          similarity_score: 0.89,
          notes: 'Generic salt equivalent; same posology requirements.',
        },
      ],
    },
    lasa_screening: {
      has_warning: false,
      prescribed_candidate: 'Augmentin 625 Duo',
      confusable_counterpart: 'None',
      tall_man_prescribed: 'amoxicillin/CLAVULANATE',
      tall_man_confused: 'N/A',
      similarity_score: 12,
      similarity_type: 'Orthographic',
      metaphone_match: false,
      clinical_risk_summary: 'Clean safety pass. No critical Look-Alike Sound-Alike collisions detected.',
      mandated_action: 'Standard pharmacist verification prior to dispensing.',
    },
    posology_explanation: {
      en: {
        summary: 'Take Augmentin 625 Duo twice daily after food for 5 days.',
        patient_instructions: 'Take 1 tablet in the morning and 1 tablet at night for 5 days. Must be taken after meals to prevent stomach upset. Complete the full 5-day course even if your symptoms improve early.',
        daily_schedule: [
          { time_slot: 'Morning ☀️', icon_key: 'Sun', dosage_label: '1 Tablet (625mg)', food_instruction: 'After breakfast' },
          { time_slot: 'Afternoon 🌤️', icon_key: 'CloudSun', dosage_label: '0 (Skip)', food_instruction: 'No dose' },
          { time_slot: 'Evening 🌇', icon_key: 'Sunset', dosage_label: '0 (Skip)', food_instruction: 'No dose' },
          { time_slot: 'Night 🌙', icon_key: 'Moon', dosage_label: '1 Tablet (625mg)', food_instruction: 'After dinner' },
        ],
        precautions: [
          'Do not stop early even if fever subsides.',
          'Take with a full glass of water.',
          'Report any persistent diarrhea or skin rash to your doctor.',
        ],
      },
      hi: {
        summary: 'ऑगमेंटिन 625 डुओ दिन में दो बार भोजन के बाद 5 दिनों तक लें।',
        patient_instructions: 'सुबह 1 गोली और रात को 1 गोली 5 दिनों के लिए लें। पेट की खराबी से बचने के लिए भोजन के बाद अवश्य लें। यदि आप पहले ही बेहतर महसूस करने लगें, तब भी 5 दिनों का पूरा कोर्स समाप्त करें।',
        daily_schedule: [
          { time_slot: 'सुबह ☀️', icon_key: 'Sun', dosage_label: '1 गोली (625mg)', food_instruction: 'नाश्ते के बाद' },
          { time_slot: 'दोपहर 🌤️', icon_key: 'CloudSun', dosage_label: '0 (छोड़ें)', food_instruction: 'कोई खुराक नहीं' },
          { time_slot: 'शाम 🌇', icon_key: 'Sunset', dosage_label: '0 (छोड़ें)', food_instruction: 'कोई खुराक नहीं' },
          { time_slot: 'रात 🌙', icon_key: 'Moon', dosage_label: '1 गोली (625mg)', food_instruction: 'रात के खाने के बाद' },
        ],
        precautions: [
          'बुखार कम होने पर भी दवा बीच में बंद न करें।',
          'पूरा एक गिलास पानी के साथ लें।',
          'यदि दस्त या त्वचा पर चकत्ते दिखाई दें तो तुरंत डॉक्टर से संपर्क करें।',
        ],
      },
      mr: {
        summary: 'ऑगमेंटिन 625 ड्युओ दिवसातून दोनदा जेवणानंतर 5 दिवसांसाठी घ्या.',
        patient_instructions: 'सकाळी 1 गोळी आणि रात्री 1 गोळी 5 दिवसांसाठी घ्या. पोटाचा त्रास टाळण्यासाठी जेवणानंतरच औषध घ्या. लक्षणे कमी झाली तरीही 5 दिवसांचा पूर्ण कोर्स पूर्ण करा.',
        daily_schedule: [
          { time_slot: 'सकाळी ☀️', icon_key: 'Sun', dosage_label: '1 गोळी (625mg)', food_instruction: 'न्याहारीनंतर' },
          { time_slot: 'दुपारी 🌤️', icon_key: 'CloudSun', dosage_label: '0 (नाही)', food_instruction: 'डोस नाही' },
          { slot: 'संध्याकाळी 🌇', icon_key: 'Sunset', dosage_label: '0 (नाही)', food_instruction: 'डोस नाही' } as any,
          { time_slot: 'रात्री 🌙', icon_key: 'Moon', dosage_label: '1 गोळी (625mg)', food_instruction: 'जेवणानंतर' },
        ],
        precautions: [
          'ताप कमी झाला तरी गोळ्या घेणे मधेच थांबवू नका.',
          'भरपूर पाण्यासोबत गोळी घ्या.',
          'जुलाब किंवा अंगावर पुरळ उठल्यास डॉक्टरांचा सल्ला घ्या.',
        ],
      },
    },
  },
};

/**
 * 2. UNCERTAIN RESPONSE FIXTURE
 * Gastro-Protective & Analgesic Inpatient Script (Pan 40 with SOS Frequency Ambiguity)
 */
export const UNCERTAIN_RESPONSE_FIXTURE: PrescriptionAnalyzeResponseDto = {
  status: 'abstain',
  meta: {
    request_id: 'req-aura-20260905-002',
    timestamp: '2026-09-05T19:26:00Z',
    processing_time_ms: 820,
    model_version: 'aura-swin-v3.4-clinical',
    pipeline_stages_completed: 7,
  },
  document_telemetry: {
    estimated_dpi: 240,
    contrast_ratio: 3.82,
    skew_angle_deg: 1.1,
    illegibility_score: 0.16,
    orientation: 'Portrait',
  },
  data: {
    accession_id: 'DEMO-RX-02',
    script_sample_key: 'rx-sample-1',
    scenario_title: 'Gastro-Protective & Analgesic Script (Ambiguity Demo)',
    scenario_subtitle: 'Illustrative demonstration scenario with cursive abbreviation ambiguity',
    difficulty_tag: 'Moderate Cursive',
    overall_status: 'NEEDS_VERIFICATION',
    document_confidence: 0.82,
    patient_info: {
      name: 'Demo Patient',
      age_gender: 'Adult / Demo',
    },
    prescriber_info: {
      name: 'Example Prescriber, M.D. (Gastroenterology)',
      qualifications: 'Consulting Gastroenterologist (Illustrative Demo)',
      registration_no: 'Demo Reg. No. 00000',
      clinic_name: 'Example Clinical Practice',
      clinic_address: 'Sample Clinic Address (Evaluation Demo)',
    },
    extracted_entities: [
      {
        field_key: 'medicine_name',
        field_label: 'Medicine Name',
        raw_value: 'Pan 40',
        normalized_value: 'Pan 40',
        confidence: 0.95,
        status: 'confident',
        stroke_source: 'Prescription Line 01 · Pen Stroke #1',
        bounding_box: { x: 12, y: 46, width: 80, height: 12 },
        explanation: 'Clear block cursive lettering matching Pantoprazole gastro-protective brand.',
      },
      {
        field_key: 'dosage',
        field_label: 'Dosage / Strength',
        raw_value: '40 mg',
        normalized_value: '40 mg',
        confidence: 0.94,
        status: 'confident',
        stroke_source: 'Prescription Line 01 · Pen Stroke #2',
        bounding_box: { x: 48, y: 46, width: 18, height: 12 },
        explanation: 'Numerals 4-0 clear with zero spatial occlusion.',
      },
      {
        field_key: 'frequency',
        field_label: 'Frequency',
        raw_value: '1-0-1 (SOS)',
        normalized_value: '1-0-1 (SOS) [Needs Verification]',
        confidence: 0.62,
        status: 'uncertain',
        stroke_source: 'Prescription Line 02 · Pen Stroke #3',
        bounding_box: { x: 68, y: 62, width: 24, height: 14 },
        explanation: 'Cursive trailing loop in "SOS" partially overlaps the preceding duration slash; ambiguity exists between PRN (as-needed) and fixed twice-daily.',
        uncertainty_reason: 'Cursive ligature overlap between "SOS" and "TDS" glyphs on line 2.',
        verification_instruction: 'Physically inspect handwritten stroke on original prescription slip. Verify with pharmacist if patient should take only when pain recurs (SOS) or fixed 1-0-1.',
        interpreted_candidate: '1-0-1 (SOS) [Runner-up: 1-0-1 TDS (0.38 confidence)]',
      },
      {
        field_key: 'duration',
        field_label: 'Duration',
        raw_value: '3-5d',
        normalized_value: '3-5 days (as needed)',
        confidence: 0.88,
        status: 'confident',
        stroke_source: 'Prescription Line 02 · Pen Stroke #4',
        bounding_box: { x: 80, y: 62, width: 14, height: 12 },
        explanation: 'Duration range numbers 3 and 5 identified with high optical contrast.',
      },
      {
        field_key: 'abbreviation',
        field_label: 'Medical Abbreviations',
        raw_value: 'AC',
        normalized_value: 'AC (Ante Cibum / 30 mins before breakfast)',
        confidence: 0.91,
        status: 'confident',
        stroke_source: 'Prescription Line 01 · Pen Stroke #3',
        bounding_box: { x: 70, y: 46, width: 12, height: 12 },
        explanation: 'Standard AC abbreviation verified for proton pump inhibitor administration.',
      },
    ],
    validation_evidence: {
      candidate_name: 'Pan 40 Tablet',
      matched_entity_name: 'Pan 40 Gastro-Resistant Tablet',
      generic_salt: 'Pantoprazole Sodium (40mg)',
      validation_status: 'cdsco_approved',
      status_badge_text: 'CDSCO Approved · RxNorm Grounded',
      rxnorm_cui: '284635',
      cdsco_schedule: 'Schedule H (Prescription Drug)',
      atc_code: 'A02BC02',
      therapeutic_class: 'Proton Pump Inhibitor (PPI) / Gastric Acid Reducer',
      indications: 'Gastroesophageal reflux disease (GERD), acid-peptic disorders, mucosal protection',
      evidence_source: 'CDSCO Pharmacopeia & US NLM RxNorm',
      alternatives: [
        {
          name: 'Pantocid 40',
          generic: 'Pantoprazole Sodium 40mg (Sun Pharma)',
          similarity_score: 0.94,
          notes: 'Standard brand equivalent.',
        },
      ],
    },
    lasa_screening: {
      has_warning: false,
      prescribed_candidate: 'Pan 40',
      confusable_counterpart: 'None',
      tall_man_prescribed: 'PANtoprazole',
      tall_man_confused: 'N/A',
      similarity_score: 10,
      similarity_type: 'Orthographic',
      metaphone_match: false,
      clinical_risk_summary: 'No critical LASA conflict detected. Main ambiguity is posology schedule.',
      mandated_action: 'Confirm SOS vs scheduled frequency with prescriber.',
    },
    posology_explanation: {
      en: {
        summary: 'Take Pan 40 once daily 30 minutes before breakfast.',
        patient_instructions: 'Take 1 tablet of Pan 40 in the morning on an empty stomach, 30 minutes before breakfast. For the fever/pain medicine, take only as needed (SOS) when temperature exceeds 100°F.',
        daily_schedule: [
          { time_slot: 'Morning ☀️', icon_key: 'Sun', dosage_label: '1 Tablet (40mg)', food_instruction: '30 mins before breakfast' },
          { time_slot: 'Afternoon 🌤️', icon_key: 'CloudSun', dosage_label: '0 (Skip)', food_instruction: 'No dose' },
          { time_slot: 'Evening 🌇', icon_key: 'Sunset', dosage_label: '0 (Skip)', food_instruction: 'No dose' },
          { time_slot: 'Night 🌙', icon_key: 'Moon', dosage_label: 'Only if SOS required', food_instruction: 'After dinner' },
        ],
        precautions: [
          'Swallow whole; do not crush or chew gastro-resistant tablets.',
          'Verify SOS fever medicine with pharmacist before taking regular doses.',
        ],
      },
      hi: {
        summary: 'पैन 40 नाश्ते से 30 मिनट पहले दिन में एक बार लें।',
        patient_instructions: 'पैन 40 की 1 गोली सुबह खाली पेट नाश्ते से 30 मिनट पहले लें। दर्द/बुखार की दवा केवल आवश्यकता पड़ने पर (SOS) लें जब बुखार 100°F से अधिक हो।',
        daily_schedule: [
          { time_slot: 'सुबह ☀️', icon_key: 'Sun', dosage_label: '1 गोली (40mg)', food_instruction: 'नाश्ते से 30 मिनट पहले' },
          { time_slot: 'दोपहर 🌤️', icon_key: 'CloudSun', dosage_label: '0 (छोड़ें)', food_instruction: 'कोई खुराक नहीं' },
          { time_slot: 'शाम 🌇', icon_key: 'Sunset', dosage_label: '0 (छोड़ें)', food_instruction: 'कोई खुराक नहीं' },
          { time_slot: 'रात 🌙', icon_key: 'Moon', dosage_label: 'केवल जरूरत पड़ने पर (SOS)', food_instruction: 'भोजन के बाद' },
        ],
        precautions: [
          'गोली को पूरा निगलें; चबाएं या तोड़ें नहीं।',
          'बुखार की गोली की खुराक फार्मासिस्ट से सत्यापित करें।',
        ],
      },
      mr: {
        summary: 'पॅन 40 न्याहारीपूर्वी 30 मिनिटे दिवसातून एकदा घ्या.',
        patient_instructions: 'सकाळी उपाशीपोटी न्याहारीच्या 30 मिनिटे आधी पॅन 40 ची 1 गोळी घ्या. तापाची गोळी फक्त गरज असल्यास (SOS) जेव्हा ताप 100°F पेक्षा जास्त असेल तेव्हाच घ्या.',
        daily_schedule: [
          { time_slot: 'सकाळी ☀️', icon_key: 'Sun', dosage_label: '1 गोळी (40mg)', food_instruction: 'न्याहारीच्या 30 मिनिटे आधी' },
          { time_slot: 'दुपारी 🌤️', icon_key: 'CloudSun', dosage_label: '0 (नाही)', food_instruction: 'डोस नाही' },
          { time_slot: 'संध्याकाळी 🌇', icon_key: 'Sunset', dosage_label: '0 (नाही)', food_instruction: 'डोस नाही' },
          { time_slot: 'रात्री 🌙', icon_key: 'Moon', dosage_label: 'फक्त गरज भासल्यास (SOS)', food_instruction: 'जेवणानंतर' },
        ],
        precautions: [
          'गोळी चावू नका; पाण्यासोबत गिळा.',
          'SOS तापाच्या गोळीचे प्रमाण फार्मसिस्टकडून तपासून घ्या.',
        ],
      },
    },
  },
};

/**
 * 3. FLAGGED RESPONSE FIXTURE
 * Pediatric Pulmonology (Prednisolone Selective Abstention Activated)
 */
export const FLAGGED_RESPONSE_FIXTURE: PrescriptionAnalyzeResponseDto = {
  status: 'abstain',
  meta: {
    request_id: 'req-aura-20260905-003',
    timestamp: '2026-09-05T19:27:00Z',
    processing_time_ms: 1100,
    model_version: 'aura-swin-v3.4-clinical',
    pipeline_stages_completed: 7,
  },
  document_telemetry: {
    estimated_dpi: 200,
    contrast_ratio: 2.95,
    skew_angle_deg: -2.1,
    illegibility_score: 0.38,
    orientation: 'Portrait',
  },
  data: {
    accession_id: 'DEMO-RX-03',
    script_sample_key: 'rx-sample-3',
    scenario_title: 'Pediatric Script (Selective Abstention Demo)',
    scenario_subtitle: 'Illustrative demonstration scenario of selective abstention on ambiguous decimal ligature',
    difficulty_tag: 'Severe Ambiguity',
    overall_status: 'SELECTIVE_ABSTAIN',
    document_confidence: 0.54,
    patient_info: {
      name: 'Demo Patient (Paediatric)',
      age_gender: 'Child / Demo',
    },
    prescriber_info: {
      name: 'Example Prescriber, M.D. (Paediatrics)',
      qualifications: 'Consultant Paediatric Specialist (Illustrative Demo)',
      registration_no: 'Demo Reg. No. 00000',
      clinic_name: 'Example Clinical Practice',
      clinic_address: 'Sample Clinic Address (Evaluation Demo)',
    },
    extracted_entities: [
      {
        field_key: 'medicine_name',
        field_label: 'Medicine Name',
        raw_value: 'Omnacortil / Prednisolone',
        normalized_value: 'Omnacortil / Prednisolone [ABSTAINED]',
        confidence: 0.74,
        status: 'uncertain',
        stroke_source: 'Prescription Line 02 · Pen Stroke #1',
        bounding_box: { x: 12, y: 48, width: 80, height: 16 },
        explanation: 'Brand Prednisolone recognized with moderate stroke confidence, but dosage ligature triggers system-level selective abstention.',
        uncertainty_reason: 'Decimal point ligature obscured by ink bleed.',
        verification_instruction: 'Check handwritten stroke on physical prescription slip; pharmacist verification required.',
      },
      {
        field_key: 'dosage',
        field_label: 'Dosage / Strength',
        raw_value: '1.0mg or 10mg?',
        normalized_value: 'AMBIGUOUS: 1.0 mg vs 10 mg [FLAGGED]',
        confidence: 0.42,
        status: 'flagged',
        stroke_source: 'Prescription Line 02 · Pen Stroke #2',
        bounding_box: { x: 52, y: 48, width: 26, height: 16 },
        explanation: 'Decimal ligature degraded. Elevated epistemic uncertainty. Dosage ambiguity exists between 1.0mg and 10mg.',
        uncertainty_reason: 'The decimal point "." is masked by ink smear and paper crease. Visually ambiguous between 1.0 mg and 10 mg.',
        verification_instruction: 'SYSTEM ABSTAINED. DO NOT DISPENSE WITHOUT CONFIRMATION FROM PRESCRIBER. Cursive ligature is ambiguous between 1.0mg and 10mg; confirm intended dose.',
        interpreted_candidate: '1.0 mg or 10 mg (Model Abstains)',
      },
      {
        field_key: 'frequency',
        field_label: 'Frequency',
        raw_value: '1-0-0',
        normalized_value: '1-0-0 (Morning) [Needs Verification]',
        confidence: 0.58,
        status: 'uncertain',
        stroke_source: 'Prescription Line 02 · Pen Stroke #3',
        bounding_box: { x: 74, y: 48, width: 18, height: 14 },
        explanation: 'Timing loop ambiguous between once-daily (1-0-0) and twice-daily (1-0-1).',
        uncertainty_reason: 'Trailing cursive loop resembles both OD and BD.',
        verification_instruction: 'Verify dosing frequency directly with prescribing paediatrician.',
      },
      {
        field_key: 'duration',
        field_label: 'Duration',
        raw_value: '3-5d',
        normalized_value: '3-5 days taper [AMBIGUOUS]',
        confidence: 0.46,
        status: 'flagged',
        stroke_source: 'Prescription Line 02 · Pen Stroke #4',
        bounding_box: { x: 80, y: 48, width: 14, height: 14 },
        explanation: 'Tapering schedule shorthand is truncated at bottom paper margin.',
        uncertainty_reason: 'Stroke clipped by lower paper fold boundary.',
        verification_instruction: 'Check prescriber clinic chart for steroid taper protocol.',
      },
      {
        field_key: 'abbreviation',
        field_label: 'Medical Abbreviations',
        raw_value: 'OD / PC',
        normalized_value: 'OD (Once Daily) / PC (After breakfast)',
        confidence: 0.76,
        status: 'uncertain',
        stroke_source: 'Prescription Line 02 · Pen Stroke #5',
        bounding_box: { x: 86, y: 48, width: 10, height: 14 },
        explanation: 'Morning post-cibum administration recommended to synchronize with diurnal cortisol rhythm.',
      },
    ],
    validation_evidence: {
      candidate_name: 'Prednisolone Oral Suspension / Tablet',
      matched_entity_name: 'Prednisolone (Omnacortil)',
      generic_salt: 'Prednisolone',
      validation_status: 'formulary_match',
      status_badge_text: 'Formulary Matched · Selective Abstention Triggered',
      rxnorm_cui: '8640',
      cdsco_schedule: 'Schedule H (Prescription Corticosteroid)',
      atc_code: 'H02AB06',
      therapeutic_class: 'Systemic Glucocorticoid / Corticosteroid',
      indications: 'Paediatric acute asthma exacerbation, severe inflammatory states',
      evidence_source: 'Indian Pharmacopoeia & US NLM RxNorm',
      alternatives: [
        {
          name: 'Omnacortil 5mg / 5mL Syrup',
          generic: 'Prednisolone 5mg/5mL',
          similarity_score: 0.88,
          notes: 'Pediatric liquid formulation.',
        },
        {
          name: 'Wysolone 10mg Dispersible Tablet',
          generic: 'Prednisolone 10mg (Pfizer)',
          similarity_score: 0.88,
          notes: 'CRITICAL: 10mg represents a 10-fold increase over 1mg. Verification mandatory.',
        },
      ],
    },
    lasa_screening: {
      has_warning: false,
      prescribed_candidate: 'Prednisolone',
      confusable_counterpart: 'Prednisone',
      tall_man_prescribed: 'prednisoLONE',
      tall_man_confused: 'PREDNISONE',
      similarity_score: 78,
      similarity_type: 'Orthographic',
      metaphone_match: true,
      clinical_risk_summary: 'Dosage ambiguity is the primary hazard. Prednisone requires hepatic conversion to Prednisolone.',
      mandated_action: 'Do NOT dispense based on automated AI inference. Mandated doctor call required.',
    },
    posology_explanation: {
      en: {
        summary: 'ATTENTION: Dosage is ambiguous (1.0mg vs 10mg). Verify with physician before administration.',
        patient_instructions: 'The system has intentionally halted automated decoding because the dosage stroke could mean either 1.0mg or 10mg. Please verify the original signed prescription slip with your pediatrician or pharmacist for exact dosage confirmation.',
        daily_schedule: [
          { time_slot: 'Morning ☀️', icon_key: 'Sun', dosage_label: 'VERIFY WITH DOCTOR', food_instruction: 'After breakfast' },
          { time_slot: 'Afternoon 🌤️', icon_key: 'CloudSun', dosage_label: '0 (None)', food_instruction: 'No dose' },
          { time_slot: 'Evening 🌇', icon_key: 'Sunset', dosage_label: '0 (None)', food_instruction: 'No dose' },
          { time_slot: 'Night 🌙', icon_key: 'Moon', dosage_label: '0 (None)', food_instruction: 'No dose' },
        ],
        precautions: [
          'DO NOT DISPENSE OR ADMINISTER WITHOUT PHYSICIAN CONFIRMATION.',
          'Verify exact dosage strength on the signed physical prescription.',
          'Always preserve the original signed prescription paper.',
        ],
      },
      hi: {
        summary: 'सावधान: खुराक अस्पष्ट है (1.0mg या 10mg)। डॉक्टर की पुष्टि के बिना बच्चे को न दें।',
        patient_instructions: 'सिस्टम ने स्वचालित प्रतिलेखन रोक दिया है क्योंकि लिखावट में खुराक 1.0mg या 10mg में अस्पष्टता है। कृपया अपने बाल रोग विशेषज्ञ या फार्मासिस्ट से पर्चे की पुष्टि कराएं।',
        daily_schedule: [
          { time_slot: 'सुबह ☀️', icon_key: 'Sun', dosage_label: 'डॉक्टर से पुष्टि करें', food_instruction: 'नाश्ते के बाद' },
          { time_slot: 'दोपहर 🌤️', icon_key: 'CloudSun', dosage_label: '0 (कुछ नहीं)', food_instruction: 'कोई खुराक नहीं' },
          { time_slot: 'शाम 🌇', icon_key: 'Sunset', dosage_label: '0 (कुछ नहीं)', food_instruction: 'कोई खुराक नहीं' },
          { time_slot: 'रात 🌙', icon_key: 'Moon', dosage_label: '0 (कुछ नहीं)', food_instruction: 'कोई खुराक नहीं' },
        ],
        precautions: [
          'डॉक्टर की पुष्टि के बिना दवा न दें।',
          'बच्चों में 10 गुना अधिक स्टेरॉयड गंभीर दुष्प्रभाव पैदा कर सकता है।',
          'मूल लिखित पर्चा हमेशा साथ रखें।',
        ],
      },
      mr: {
        summary: 'लक्ष द्या: डोस अस्पष्ट आहे (1.0mg की 10mg). डॉक्टरांच्या खात्रीशिवाय बालकाला औषध देऊ नका.',
        patient_instructions: 'सिस्टिमने मुद्दाम ऑटोमॅटिक डिकोडिंग थांबवले आहे कारण हस्ताक्षरात डोस 1.0mg किंवा 10mg असू शकतो. 21 किलोच्या मुलाला 10 पट जास्त स्टिरॉइड देणे धोकादायक ठरू शकते. मूळ कागदी प्रिस्क्रिप्शन बालरोगतज्ज्ञ किंवा फार्मसिस्टला दाखवून अचूक डोस तपासून घ्या.',
        daily_schedule: [
          { time_slot: 'सकाळी ☀️', icon_key: 'Sun', dosage_label: 'डॉक्टरांकडून तपासा', food_instruction: 'न्याहारीनंतर' },
          { time_slot: 'दुपारी 🌤️', icon_key: 'CloudSun', dosage_label: '0 (काही नाही)', food_instruction: 'डोस नाही' },
          { time_slot: 'संध्याकाळी 🌇', icon_key: 'Sunset', dosage_label: '0 (काही नाही)', food_instruction: 'डोस नाही' },
          { time_slot: 'रात्री 🌙', icon_key: 'Moon', dosage_label: '0 (काही नाही)', food_instruction: 'डोस नाही' },
        ],
        precautions: [
          'डॉक्टरांच्या लेखी पुष्टीशिवाय औषध देऊ नका.',
          'लहान मुलांमध्ये स्टिरॉइडचा 10 पट जास्त डोस धोकादायक ठरू शकतो.',
          'डॉक्टरांचे मूळ स्वाक्षरी असलेले प्रिस्क्रिप्शन सोबत ठेवा.',
        ],
      },
    },
  },
};

/**
 * 4. LASA WARNING RESPONSE FIXTURE
 * Cardiometabolic Care (Metformin vs Metronidazole Collision)
 */
export const LASA_WARNING_RESPONSE_FIXTURE: PrescriptionAnalyzeResponseDto = {
  status: 'abstain',
  meta: {
    request_id: 'req-aura-20260905-004',
    timestamp: '2026-09-05T19:28:00Z',
    processing_time_ms: 910,
    model_version: 'aura-swin-v3.4-clinical',
    pipeline_stages_completed: 7,
  },
  document_telemetry: {
    estimated_dpi: 260,
    contrast_ratio: 4.12,
    skew_angle_deg: 0.8,
    illegibility_score: 0.12,
    orientation: 'Portrait',
  },
  data: {
    accession_id: 'DEMO-RX-04',
    script_sample_key: 'rx-sample-2',
    scenario_title: 'Demo Case 04 (Look-Alike Sound-Alike Similarity Example)',
    scenario_subtitle: 'Illustrative orthographic & phonetic similarity flag between Metformin and Metronidazole',
    difficulty_tag: 'LASA Similarity',
    overall_status: 'SAFETY_ALERT',
    document_confidence: 0.85,
    patient_info: {
      name: 'Demo Patient',
      age_gender: '56Y / Example Record',
    },
    prescriber_info: {
      name: 'Example Prescriber, M.D.',
      qualifications: 'Example Clinical Consultant (Demo)',
      registration_no: 'Demo Reg. No. 00000',
      clinic_name: 'Example Clinical Practice',
      clinic_address: 'Demo Medical Center · Illustrative Record',
    },
    extracted_entities: [
      {
        field_key: 'medicine_name',
        field_label: 'Medicine Name',
        raw_value: 'Metformin 500',
        normalized_value: 'Glyciphage 500 / Metformin',
        confidence: 0.84,
        status: 'confident',
        stroke_source: 'Prescription Line 01 · Pen Stroke #1',
        bounding_box: { x: 12, y: 32, width: 80, height: 16 },
        explanation: 'Cursive stroke decoded to Metformin, but triggers orthographic/phonetic screening alert with Metronidazole.',
      },
      {
        field_key: 'dosage',
        field_label: 'Dosage / Strength',
        raw_value: '500 mg',
        normalized_value: '500 mg',
        confidence: 0.92,
        status: 'confident',
        stroke_source: 'Prescription Line 01 · Pen Stroke #2',
        bounding_box: { x: 55, y: 32, width: 18, height: 14 },
        explanation: 'Numerical strength 500 mg clear and standard for initial oral hypoglycaemic therapy.',
      },
      {
        field_key: 'frequency',
        field_label: 'Frequency',
        raw_value: '1-0-1',
        normalized_value: '1-0-1 (Twice daily with major meals)',
        confidence: 0.91,
        status: 'confident',
        stroke_source: 'Prescription Line 01 · Pen Stroke #3',
        bounding_box: { x: 74, y: 32, width: 16, height: 14 },
        explanation: 'Twice daily posology matching standard clinical glycemic protocol.',
      },
      {
        field_key: 'duration',
        field_label: 'Duration',
        raw_value: 'Continuous (30d refill)',
        normalized_value: 'Continuous (Monthly refill x 30 days)',
        confidence: 0.9,
        status: 'confident',
        stroke_source: 'Prescription Line 01 · Pen Stroke #4',
        bounding_box: { x: 80, y: 32, width: 12, height: 14 },
        explanation: 'Chronic diabetes maintenance duration verified.',
      },
      {
        field_key: 'abbreviation',
        field_label: 'Medical Abbreviations',
        raw_value: 'CC',
        normalized_value: 'CC (Cum Cibo / With major meals)',
        confidence: 0.89,
        status: 'confident',
        stroke_source: 'Prescription Line 01 · Pen Stroke #5',
        bounding_box: { x: 88, y: 32, width: 8, height: 14 },
        explanation: 'Administration with meals recommended to minimize gastrointestinal discomfort.',
      },
    ],
    validation_evidence: {
      candidate_name: 'Metformin Hydrochloride 500mg Tablet',
      matched_entity_name: 'Glyciphage 500 / Metformin 500mg',
      generic_salt: 'Metformin Hydrochloride (500mg)',
      validation_status: 'cdsco_approved',
      status_badge_text: 'CDSCO Approved · Formulary Grounded',
      rxnorm_cui: '6809',
      cdsco_schedule: 'Schedule H (Prescription Drug)',
      atc_code: 'A10BA02',
      therapeutic_class: 'Biguanide Antihyperglycemic / Type 2 Diabetes Care',
      indications: 'Type 2 diabetes mellitus glycemic management in adults',
      evidence_source: 'CDSCO Drug Control Administration & US NLM RxNorm',
      alternatives: [
        {
          name: 'Glycomet 500 (USV)',
          generic: 'Metformin 500mg',
          similarity_score: 0.96,
          notes: 'Standard bioequivalent biguanide.',
        },
        {
          name: 'Metrogyl 400 (J.B. Chemicals)',
          generic: 'Metronidazole 400mg (CRITICAL LASA COLLISION)',
          similarity_score: 0.82,
          notes: 'Antimicrobial agent. Clinician must verify patient has diabetes, NOT amoebic dysentery.',
        },
      ],
    },
    lasa_screening: {
      has_warning: true,
      prescribed_candidate: 'Metformin',
      confusable_counterpart: 'Metronidazole',
      tall_man_prescribed: 'metFORMIN',
      tall_man_confused: 'metRONIDAZOLE',
      similarity_score: 82,
      similarity_type: 'Orthographic & Phonetic',
      metaphone_match: true,
      clinical_risk_summary: 'High phonetic and cursive visual ligature similarity. Metformin is an oral biguanide antihyperglycemic for diabetes; Metronidazole is an antimicrobial nitroimidazole for amoebic infections. Confusion could cause severe hypoglycemia or untreated infection.',
      mandated_action: 'The system detected possible similarity. It has NOT determined the correct medicine. Clinician and dispensing pharmacist confirmation required before dispensing.',
    },
    posology_explanation: {
      en: {
        summary: 'Take Metformin 500mg twice daily with major meals for diabetes.',
        patient_instructions: 'Take 1 tablet with breakfast and 1 tablet with dinner. Always take with or immediately after food to minimize stomach upset. Confirm with pharmacist that this is Metformin (for blood sugar) and NOT Metronidazole.',
        daily_schedule: [
          { time_slot: 'Morning ☀️', icon_key: 'Sun', dosage_label: '1 Tablet (500mg)', food_instruction: 'With breakfast' },
          { time_slot: 'Afternoon 🌤️', icon_key: 'CloudSun', dosage_label: '0 (Skip)', food_instruction: 'No dose' },
          { time_slot: 'Evening 🌇', icon_key: 'Sunset', dosage_label: '0 (Skip)', food_instruction: 'No dose' },
          { time_slot: 'Night 🌙', icon_key: 'Moon', dosage_label: '1 Tablet (500mg)', food_instruction: 'With dinner' },
        ],
        precautions: [
          'CRITICAL: Ensure your pharmacist dispenses Metformin for blood sugar, not Metronidazole.',
          'Do not take on an empty stomach.',
          'Carry glucose tablets or candy in case of low blood sugar symptoms.',
        ],
      },
      hi: {
        summary: 'मधुमेह के लिए भोजन के साथ दिन में दो बार मेटफॉर्मिन 500mg लें।',
        patient_instructions: 'नाश्ते के साथ 1 गोली और रात के खाने के साथ 1 गोली लें। पेट की परेशानी कम करने के लिए हमेशा भोजन के साथ लें। फार्मासिस्ट से पुष्टि करें कि यह मेटफॉर्मिन (ब्लड शुगर के लिए) है, मेट्रोनिडाजोल नहीं।',
        daily_schedule: [
          { time_slot: 'सुबह ☀️', icon_key: 'Sun', dosage_label: '1 गोली (500mg)', food_instruction: 'नाश्ते के साथ' },
          { time_slot: 'दोपहर 🌤️', icon_key: 'CloudSun', dosage_label: '0 (छोड़ें)', food_instruction: 'कोई खुराक नहीं' },
          { time_slot: 'शाम 🌇', icon_key: 'Sunset', dosage_label: '0 (छोड़ें)', food_instruction: 'कोई खुराक नहीं' },
          { time_slot: 'रात 🌙', icon_key: 'Moon', dosage_label: '1 गोली (500mg)', food_instruction: 'रात के खाने के साथ' },
        ],
        precautions: [
          'महत्वपूर्ण: सुनिश्चित करें कि फार्मासिस्ट मेटफॉर्मिन दे, मेट्रोनिडाजोल नहीं।',
          'खाली पेट न लें।',
          'ब्लड शुगर कम होने के लक्षणों के लिए पास में मीठा रखें।',
        ],
      },
      mr: {
        summary: 'मधुमेहासाठी जेवणासोबत दिवसातून दोनदा मेटफॉर्मिन 500mg घ्या.',
        patient_instructions: 'सकाळी न्याहारीसोबत 1 गोळी आणि रात्री जेवणासोबत 1 गोळी घ्या. पोटाचा त्रास टाळण्यासाठी नेहमी अन्नासोबतच घ्या. फार्मसिस्टकडून खात्री करा की हे मेटफॉर्मिन (साखरेसाठी) आहे, मेट्रोनिडाझोल नाही.',
        daily_schedule: [
          { time_slot: 'सकाळी ☀️', icon_key: 'Sun', dosage_label: '1 गोळी (500mg)', food_instruction: 'न्याहारीसोबत' },
          { time_slot: 'दुपारी 🌤️', icon_key: 'CloudSun', dosage_label: '0 (नाही)', food_instruction: 'डोस नाही' },
          { time_slot: 'संध्याकाळी 🌇', icon_key: 'Sunset', dosage_label: '0 (नाही)', food_instruction: 'डोस नाही' },
          { time_slot: 'रात्री 🌙', icon_key: 'Moon', dosage_label: '1 गोळी (500mg)', food_instruction: 'जेवणासोबत' },
        ],
        precautions: [
          'महत्त्वाचे: फार्मसिस्टकडून मेटफॉर्मिन दिल्याची खात्री करा, मेट्रोनिडाझोल नाही.',
          'उपाशीपोटी घेऊ नका.',
          'साखर कमी झाल्यास खाण्यासाठी जवळ गोड पदार्थ ठेवा.',
        ],
      },
    },
  },
};

/**
 * 5. ERROR RESPONSE FIXTURES
 * Authentic FastAPI HTTPException error responses
 */
export const FASTAPI_VALIDATION_ERROR_FIXTURE: FastApiHttpErrorDto = {
  detail: [
    {
      loc: ['body', 'file'],
      msg: 'Document image resolution (420x600 px) falls below the minimum required diagnostic threshold of 800x1200 px for optical ligature extraction.',
      type: 'value_error.resolution_too_low',
    },
  ],
  error_code: 'RESOLUTION_UNACCEPTABLE',
  request_id: 'err-aura-422-res-fail',
};

export const FASTAPI_SERVER_ERROR_FIXTURE: FastApiHttpErrorDto = {
  detail: 'Internal GPU Inference Worker Failure: CUDA out-of-memory while executing cross-attention decoder on Swin-Large backbone.',
  error_code: 'INFERENCE_WORKER_FAILURE',
  request_id: 'err-aura-500-gpu-oom',
};

export const FASTAPI_GATEWAY_TIMEOUT_FIXTURE: FastApiHttpErrorDto = {
  detail: 'CDSCO Drug Database & RxNorm Formulary Gateway connection timed out after 15,000ms. Upstream microservice unresponsive.',
  error_code: 'ONTOLOGY_GATEWAY_TIMEOUT',
  request_id: 'err-aura-504-timeout',
};
