"""
Phase 11: Deterministic Test and Evaluation Mock Fixtures.
Provides standard fixtures for testing posology explanation generation,
eligibility transitions, numeric fidelity, medicine name preservation,
and safety validator rejection across English, Hindi, and Marathi.

All fixtures in this file are clearly identified as DEVELOPMENT/TEST FIXTURES.
"""

from typing import Any, Dict, List

DEVELOPMENT_FIXTURE_NOTICE = (
    "DEVELOPMENT TEST FIXTURE ONLY: Not for clinical or diagnostic use."
)

EXPLANATION_FIXTURES: Dict[str, Dict[str, Any]] = {
    # 1. Fully confident prescription
    "1_fully_confident": {
        "fixture_id": "FIX-11-01",
        "description": "Confident, validated prescription with complete posology (Paracetamol 500 mg, twice daily, 5 days)",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-CONF-001",
            "medicine_name": "Paracetamol",
            "dosage": "500 mg",
            "frequency": "twice daily",
            "duration": "5 days",
            "candidate_status": "confident",
            "validation_status": "validated",
            "abstention_decision": "accepted",
            "requires_human_verification": False,
            "has_lasa_conflict": False,
        },
        "expected_status": "eligible",
        "expected_in_en": ["Paracetamol", "500 mg", "twice daily", "5 days"],
        "expected_in_hi": ["Paracetamol", "500 mg", "दो बार", "5 दिन"],
        "expected_in_mr": ["Paracetamol", "500 mg", "दोन वेळा", "5 दिवस"],
    },
    # 2. Missing dosage
    "2_missing_dosage": {
        "fixture_id": "FIX-11-02",
        "description": "Prescription with missing dosage field",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-MISS-DOS",
            "medicine_name": "Amoxicillin",
            "dosage": None,
            "frequency": "three times daily",
            "duration": "7 days",
            "candidate_status": "confident",
            "validation_status": "validated",
            "abstention_decision": "accepted",
            "requires_human_verification": False,
            "has_lasa_conflict": False,
        },
        "expected_status": "eligible",
        "expected_in_en": ["Amoxicillin", "as written on the prescription"],
    },
    # 3. Missing frequency
    "3_missing_frequency": {
        "fixture_id": "FIX-11-03",
        "description": "Prescription with missing frequency field",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-MISS-FREQ",
            "medicine_name": "Metformin",
            "dosage": "500 mg",
            "frequency": None,
            "duration": "30 days",
            "candidate_status": "confident",
            "validation_status": "validated",
            "abstention_decision": "accepted",
            "requires_human_verification": False,
            "has_lasa_conflict": False,
        },
        "expected_status": "eligible",
        "expected_in_en": ["Metformin", "500 mg"],
    },
    # 4. Missing duration
    "4_missing_duration": {
        "fixture_id": "FIX-11-04",
        "description": "Prescription with missing duration field",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-MISS-DUR",
            "medicine_name": "Pantoprazole",
            "dosage": "40 mg",
            "frequency": "once daily",
            "duration": None,
            "candidate_status": "confident",
            "validation_status": "validated",
            "abstention_decision": "accepted",
            "requires_human_verification": False,
            "has_lasa_conflict": False,
        },
        "expected_status": "eligible",
        "expected_in_en": ["Pantoprazole", "40 mg", "once daily"],
    },
    # 5. Uncertain medicine
    "5_uncertain_medicine": {
        "fixture_id": "FIX-11-05",
        "description": "Medicine name has low visual confidence / ambiguous cursive",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-UNC-005",
            "medicine_name": "Amoxi...",
            "dosage": "250 mg",
            "frequency": "twice daily",
            "duration": "5 days",
            "candidate_status": "uncertain",
            "validation_status": "uncertain",
            "abstention_decision": "flagged",
            "requires_human_verification": True,
            "has_lasa_conflict": False,
        },
        "expected_status": "restricted",
        "expected_in_en": ["could not be read with sufficient confidence"],
        "expected_in_hi": ["पर्याप्त विश्वास के साथ पढ़ा नहीं जा सका"],
        "expected_in_mr": ["पुरेशा खात्रीने वाचता आले नाही"],
    },
    # 6. Multiple candidate medicine
    "6_multiple_candidates": {
        "fixture_id": "FIX-11-06",
        "description": "Ambiguous handwriting matching multiple formulary candidates",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-MULT-006",
            "medicine_name": "Cetirizine",
            "dosage": "10 mg",
            "frequency": "at bedtime",
            "duration": "10 days",
            "candidate_status": "uncertain",
            "validation_status": "not_validated",
            "abstention_decision": "flagged",
            "requires_human_verification": True,
            "has_lasa_conflict": False,
        },
        "expected_status": "restricted",
    },
    # 7. Phase 9 abstention
    "7_phase9_abstention": {
        "fixture_id": "FIX-11-07",
        "description": "Autonomous output blocked by Phase 9 abstention policy",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-ABST-007",
            "medicine_name": "UnclearMed",
            "dosage": "100 mg",
            "frequency": "daily",
            "duration": "3 days",
            "candidate_status": "abstained",
            "validation_status": "uncertain",
            "abstention_decision": "abstained",
            "requires_human_verification": True,
            "has_lasa_conflict": False,
        },
        "expected_status": "abstained",
        "expected_in_en": ["verification against the original prescription"],
        "expected_in_hi": ["मूल प्रिस्क्रिप्शन से दवा के विवरण की पुष्टि"],
        "expected_in_mr": ["मूळ प्रिस्क्रिप्शनशी औषधाच्या तपशीलाची पडताळणी"],
    },
    # 8. Phase 10 LASA conflict
    "8_phase10_lasa_conflict": {
        "fixture_id": "FIX-11-08",
        "description": "Phase 10 LASA similarity conflict detected between Prednisone and Prednisolone",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-LASA-008",
            "medicine_name": "Prednisone",
            "dosage": "10 mg",
            "frequency": "once daily",
            "duration": "5 days",
            "candidate_status": "confident",
            "validation_status": "validated",
            "abstention_decision": "accepted",
            "requires_human_verification": True,
            "has_lasa_conflict": True,
            "confusable_counterpart": "Prednisolone",
        },
        "expected_status": "restricted",
        "expected_in_en": ["Similar medicine names were detected", "Please verify"],
        "expected_in_hi": ["मिलते-जुलते दवा के नाम पाए गए हैं"],
        "expected_in_mr": ["सारखी औषधांची नावे आढळली आहेत"],
    },
    # 9. Human-confirmed correction
    "9_human_confirmed_correction": {
        "fixture_id": "FIX-11-09",
        "description": "Human pharmacist corrected raw AI 'Amox...' to 'Amoxicillin'",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-CORR-009",
            "medicine_name": "Amox...",
            "dosage": "500 mg",
            "frequency": "three times daily",
            "duration": "7 days",
            "candidate_status": "uncertain",
            "validation_status": "validated",
            "abstention_decision": "accepted",
            "requires_human_verification": False,
            "has_lasa_conflict": False,
            "human_verification_status": "corrected",
            "human_verified_value": "Amoxicillin",
        },
        "expected_status": "eligible",
        "expected_in_en": ["Amoxicillin", "500 mg"],
        "expected_audit_original": "Amox...",
    },
    # 10. Human-marked unreadable
    "10_human_marked_unreadable": {
        "fixture_id": "FIX-11-10",
        "description": "Pharmacist examined handwriting and explicitly marked entity as unreadable",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-UNREAD-010",
            "medicine_name": "IllegibleStroke",
            "dosage": None,
            "frequency": None,
            "duration": None,
            "candidate_status": "abstained",
            "validation_status": "unverified",
            "abstention_decision": "abstained",
            "requires_human_verification": True,
            "has_lasa_conflict": False,
            "human_verification_status": "unreadable",
        },
        "expected_status": "abstained",
        "expected_in_en": ["could not be confirmed from the prescription"],
        "expected_in_hi": ["पुष्टि नहीं हो सकी"],
        "expected_in_mr": ["पुष्टी करता आली नाही"],
    },
    # 11. Dosage with decimal
    "11_dosage_with_decimal": {
        "fixture_id": "FIX-11-11",
        "description": "Dosage containing explicit decimal quantity (2.5 mL)",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-DEC-011",
            "medicine_name": "Syrup Paracetamol",
            "dosage": "2.5 mL",
            "frequency": "three times daily",
            "duration": "3 days",
            "candidate_status": "confident",
            "validation_status": "validated",
            "abstention_decision": "accepted",
            "requires_human_verification": False,
            "has_lasa_conflict": False,
        },
        "expected_status": "eligible",
        "expected_in_en": ["Syrup Paracetamol", "2.5 mL", "3 days"],
        "expected_in_hi": ["Syrup Paracetamol", "2.5 mL", "3 दिन"],
        "expected_in_mr": ["Syrup Paracetamol", "2.5 mL", "3 दिवस"],
    },
    # 12. Multi-digit dosage
    "12_multidigit_dosage": {
        "fixture_id": "FIX-11-12",
        "description": "High-magnitude multi-digit dosage (1000 mg)",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-MULTIDIG-012",
            "medicine_name": "Ceftriaxone",
            "dosage": "1000 mg",
            "frequency": "once daily",
            "duration": "1 day",
            "candidate_status": "confident",
            "validation_status": "validated",
            "abstention_decision": "accepted",
            "requires_human_verification": False,
            "has_lasa_conflict": False,
        },
        "expected_status": "eligible",
        "expected_in_en": ["Ceftriaxone", "1000 mg", "1 day"],
    },
    # 13. Frequency preservation
    "13_frequency_preservation": {
        "fixture_id": "FIX-11-13",
        "description": "Preservation of 1-0-1 posology schedule",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-FREQ-013",
            "medicine_name": "Ciprofloxacin",
            "dosage": "500 mg",
            "frequency": "1-0-1",
            "duration": "5 days",
            "candidate_status": "confident",
            "validation_status": "validated",
            "abstention_decision": "accepted",
            "requires_human_verification": False,
            "has_lasa_conflict": False,
        },
        "expected_status": "eligible",
        "expected_in_en": ["twice daily"],
        "expected_in_hi": ["दिन में दो बार"],
        "expected_in_mr": ["दिवसातून दोन वेळा"],
    },
    # 14. Duration preservation
    "14_duration_preservation": {
        "fixture_id": "FIX-11-14",
        "description": "Duration preservation over 14 days",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-DUR-014",
            "medicine_name": "Amoxicillin-Clavulanate",
            "dosage": "625 mg",
            "frequency": "twice daily",
            "duration": "14 days",
            "candidate_status": "confident",
            "validation_status": "validated",
            "abstention_decision": "accepted",
            "requires_human_verification": False,
            "has_lasa_conflict": False,
        },
        "expected_status": "eligible",
        "expected_in_en": ["14 days"],
        "expected_in_hi": ["14 दिनों"],
        "expected_in_mr": ["14 दिवस"],
    },
    # 15. English explanation
    "15_english_explanation": {
        "fixture_id": "FIX-11-15",
        "description": "Standard English posology narrative with complete facts",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-EN-015",
            "medicine_name": "Ibuprofen",
            "dosage": "400 mg",
            "frequency": "twice daily",
            "duration": "3 days",
            "candidate_status": "confident",
            "validation_status": "validated",
        },
        "expected_status": "eligible",
        "expected_text": "Ibuprofen is listed with a dose of 400 mg, to be taken twice daily, for 3 days, as written on the prescription.",
    },
    # 16. Hindi explanation
    "16_hindi_explanation": {
        "fixture_id": "FIX-11-16",
        "description": "Standard Hindi posology narrative with complete facts",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-HI-016",
            "medicine_name": "Ibuprofen",
            "dosage": "400 mg",
            "frequency": "twice daily",
            "duration": "3 days",
            "candidate_status": "confident",
            "validation_status": "validated",
        },
        "expected_status": "eligible",
        "expected_text": "प्रिस्क्रिप्शन में Ibuprofen की मात्रा 400 mg लिखी है। इसे दिन में दो बार, 3 days तक लेने के लिए लिखा गया है।",
    },
    # 17. Marathi explanation
    "17_marathi_explanation": {
        "fixture_id": "FIX-11-17",
        "description": "Standard Marathi posology narrative with complete facts",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-MR-017",
            "medicine_name": "Ibuprofen",
            "dosage": "400 mg",
            "frequency": "twice daily",
            "duration": "3 days",
            "candidate_status": "confident",
            "validation_status": "validated",
        },
        "expected_status": "eligible",
        "expected_text": "प्रिस्क्रिप्शनमध्ये Ibuprofen ची मात्रा 400 mg लिहिलेली आहे. हे दिवसातून दोन वेळा, 3 days घेण्यासाठी लिहिले आहे.",
    },
    # 18. Unsupported-fact rejection
    "18_unsupported_fact_rejection": {
        "fixture_id": "FIX-11-18",
        "description": "Explanation text containing hallucinated clinical diagnosis ('for fever')",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "mutated_text": "Paracetamol is listed with a dose of 500 mg for fever, as written on the prescription.",
        "expected_validation": False,
        "expected_detail": "Unsupported clinical claim detected",
    },
    # 19. Numeric mutation rejection
    "19_numeric_mutation_rejection": {
        "fixture_id": "FIX-11-19",
        "description": "Explanation text mutating 500 mg into 250 mg",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "source_dosage": "500 mg",
        "mutated_text": "Paracetamol is listed with a dose of 250 mg as written on the prescription.",
        "expected_validation": False,
        "expected_detail": "Numeric mutation or omission",
    },
    # 20. Medicine-name mutation rejection
    "20_medicine_mutation_rejection": {
        "fixture_id": "FIX-11-20",
        "description": "Explanation text mutating Paracetamol to Aspirin",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "source_medicine": "Paracetamol",
        "mutated_text": "Aspirin is listed with a dose of 500 mg as written on the prescription.",
        "expected_validation": False,
        "expected_detail": "Medicine name 'Paracetamol' not found",
    },
    # 21. Explanation service unavailable
    "21_service_unavailable": {
        "fixture_id": "FIX-11-21",
        "description": "System failure or service degraded state",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-UNAVAIL-021",
            "medicine_name": "Paracetamol",
            "dosage": "500 mg",
            "is_service_healthy": False,
        },
        "expected_status": "unavailable",
        "expected_in_en": ["currently unavailable"],
    },
    # 22. Invalid structured input
    "22_invalid_structured_input": {
        "fixture_id": "FIX-11-22",
        "description": "Input with empty/missing medicine name and empty fields",
        "notice": DEVELOPMENT_FIXTURE_NOTICE,
        "input": {
            "prescription_id": "RX-INV-022",
            "medicine_name": "",
            "dosage": None,
        },
        "expected_status": "abstained",
    },
}
