"""
Canonical AI Multimodal Architecture Module
Bridge to backend.app.multimodal for research import consistency.
"""

from backend.app.multimodal import (
    MultimodalConfig,
    BoundingBox,
    VisualEvidence,
    ExtractedField,
    ExtractedMedicine,
    ModelMetadata,
    PrescriptionExtractionResult,
    FieldStatus,
    FieldPresence,
    ExtractionState,
    EvidenceType,
    EvidenceSource,
    SYSTEM_INSTRUCTION_V1,
    USER_INSTRUCTION_V1,
    resolve_visual_evidence,
    parse_multimodal_response,
    MultimodalParseError,
    finalize_extraction_result,
    postprocess_extracted_medicine,
    postprocess_extracted_field,
    build_aggregate_fields,
    IMultimodalModelAdapter,
    GeminiMultimodalAdapter,
    MockMultimodalModelAdapter,
    MultimodalExtractionService,
)

__all__ = [
    "MultimodalConfig",
    "BoundingBox",
    "VisualEvidence",
    "ExtractedField",
    "ExtractedMedicine",
    "ModelMetadata",
    "PrescriptionExtractionResult",
    "FieldStatus",
    "FieldPresence",
    "ExtractionState",
    "EvidenceType",
    "EvidenceSource",
    "SYSTEM_INSTRUCTION_V1",
    "USER_INSTRUCTION_V1",
    "resolve_visual_evidence",
    "parse_multimodal_response",
    "MultimodalParseError",
    "finalize_extraction_result",
    "postprocess_extracted_medicine",
    "postprocess_extracted_field",
    "build_aggregate_fields",
    "IMultimodalModelAdapter",
    "GeminiMultimodalAdapter",
    "MockMultimodalModelAdapter",
    "MultimodalExtractionService",
]
